spec:
  source: ''
  conda: ''
  desired_state: online
  owner: shapira
  functions:
  - url: model_server.py
    name: llm-server
    kind: serving
    image: gcr.io/iguazio/llm-serving:1.7.2
  - url: train.py
    name: train
    kind: job
    image: gcr.io/iguazio/monitoring-demo-adapters:1.7.2
  - url: metric_sample.py
    name: metric-sample
    kind: job
    image: mlrun/mlrun
  - url: generate_ds.py
    name: generate-ds
    kind: job
    image: gcr.io/iguazio/llm-serving:1.7.2
  default_image: gcr.io/iguazio/llm-serving:1.7.2
  params:
    default_image: gcr.io/iguazio/llm-serving:1.7.2
    node_selector:
      alpha.eksctl.io/nodegroup-name: added-a10x4
metadata:
  created: '2025-01-26T18:42:15.666000'
  name: llm-monitoring
status:
  state: online
kind: project
